config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kittens }
    end
  end

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to kittens_path, notice: 'Successfully created Kitten'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @kitten.update(kitten_params)
      redirect_to kittens_path, notice: 'Successfully updated Kitten'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten.destroy
    redirect_to kittens_path, notice: 'Kitten was deleted'
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
  <%= f.label :name, 'Name:' %>
  <%= f.text_field :name %>
  <%= f.label :age, 'Age:' %>
  <%= f.number_field :age %>
  <%= f.label :cuteness, 'Cuteness' %>
  <%= f.range_field :cuteness, in: 1..10 %>
  <%= f.label :softness, 'Softness' %>
  <%= f.range_field :softness, in: 1..10 %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/kittens/_kitten.html.erb
<div class="mb-3 card card-body">
  <div class="me-4">
      <li>Name: <%= kitten.name %></li>
      <li>Age: <%= kitten.age %></li>
      <li>Cuteness: <%= kitten.cuteness %>/10</li>
      <li>Softness: <%= kitten.softness %>/10</li>
      <%= link_to 'Show details', kitten_path(kitten) %>
      <%= link_to 'Edit', edit_kitten_path(kitten) %>
      <%= link_to 'Delete', kitten_path(kitten), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/kittens/edit.html.erb
<h2>Edit Kitten</h2>
<%= render partial: 'form' %>
<%= link_to 'Delete', @kitten, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<%= render @kittens %>
<%= link_to 'Add Kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h2>Add Kitten</h2>
<%= render partial: 'form' %>

app/views/kittens/show.html.erb
<h1>Kitten Info</h1>
<div class="mb-3 card card-body">
  <div class="me-4">
      <li>Name: <%= @kitten.name %></li>
      <li>Age: <%= @kitten.age %></li>
      <li>Cuteness: <%= @kitten.cuteness %>/10</li>
      <li>Softness: <%= @kitten.softness %>/10</li>
      <%= link_to 'Edit', edit_kitten_path(@kitten) %>
      <%= link_to 'Delete', kitten_path(@kitten), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>